_BASE_: ../kittimots/maskformer2_R50_bs16_50ep.yaml
DATASETS:
  TRAIN: ("motschallenge_train",)
  TEST: ("motschallenge_val",)
TEST:
  EVAL_PERIOD: 0
  GT_DIR: "data/MOTS/train/"
  OUTPUT_DIR: "new/"
  EVAL_MODE: "train"
  SEQMAP: "external/mots_tools/mots_eval/val_MOTSchallenge_small.seqmap"
