MODEL:
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_backbone"
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  RESNETS:
    DEPTH: 50
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    #NORM: "SyncBN"  # use syncbn for cityscapes dataset, doesn't work for single GPU.
    RES5_MULTI_GRID: [1, 1, 1]  # not used
DATASETS:
  TRAIN: ("cityscapes_vps_train",)
  TEST: ("cityscapes_vps_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.0001
  MAX_ITER: 90000
  STEPS: (13000,)
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
INPUT:
  DATASET_MAPPER_NAME: "cityscapes_vps"
  IGNORE_VALUE: -100
  SAMPLING_FRAME_NUM: 4
  MIN_SIZE_TRAIN: 960,1024
  MIN_SIZE_TRAIN_SAMPLING: "choice_by_clip"
  RANDOM_FLIP: "flip_by_clip"
  MIN_SIZE_TEST: 1024
  # MAX_SIZE_TRAIN: 4096
  # MAX_SIZE_TEST: 2048
  AUGMENTATIONS: []
  CROP:
    ENABLED: False
    # TYPE: "absolute_range"
    # SIZE: (512, 1024)
    SINGLE_CATEGORY_MAX_AREA: 1.0
  COLOR_AUG_SSD: True
  SIZE_DIVISIBILITY: -1
  FORMAT: "RGB"
  SUBSET: False
TEST:
  EVAL_PERIOD: 5000
  AUG:
    ENABLED: False
    MIN_SIZES: [512, 768, 1024, 1280, 1536, 1792]
    MAX_SIZE: 4096
    FLIP: True
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4
VERSION: 2
